### ISSUE TITLE
windows上编译nms_rotated，总是失败

### ISSUE THREAD

**Issue by liuwenhaha** [hukaixuan19970627/yolov5_obb#317]
环境：windows 10
           cuda 11.3
           pytorch 1.10
编译一个小时了，总是出问题，有没有大佬能帮我看看
![image](https://user-images.githubusercontent.com/18018760/168196731-5515331c-d370-4a68-a001-1802f4c09d33.png)

**Comment by LUO77123** [comment]
按照作者的说明，是可以配好的

**Comment by hukaixuan19970627** [comment]
![image](https://user-images.githubusercontent.com/72599120/168231174-54de4d21-00d7-4973-ac13-9f7fad4d9837.png)

**Comment by liuwenhaha** [comment]
> ![image](https://user-images.githubusercontent.com/72599120/168231174-54de4d21-00d7-4973-ac13-9f7fad4d9837.png)

大佬，我一开始看的就是这个链接，把.cu文件也换了，然后，中文注释都删了，最后还是一样报错

**Comment by hukaixuan19970627** [comment]
把以下命令运行一遍，运行结果截个图看看
‘’‘python
nvcc -V
nvidia-smi
python
>>> import torch
>>> torch.version.cuda()
’‘’

**Comment by liuwenhaha** [comment]
> 把以下命令运行一遍，运行结果截个图看看
> 
> ```python
> nvcc -V
> nvidia-smi
> python
> >>> import torch
> >>> torch.version.cuda()
> ```

1、nvcc -V和nvidia-smi
![image](https://user-images.githubusercontent.com/18018760/168237289-c9f19772-feb0-4efd-83bf-7fd1a8ea121b.png)
2、torch.version.cuda()

**Comment by hukaixuan19970627** [comment]
那我无能为力了，不建议windows的原因就是因为每个人都能遇到各式各样的错误，目前只能根据报错提示一点点的改。要是你不急着用的话，七月份之前我更一版不需要用cuda编译的代码

**Comment by liuwenhaha** [comment]
> 那我无能为力了，不建议windows的原因就是因为每个人都能遇到各式各样的错误，目前只能根据报错提示一点点的改。要是你不急着用的话，七月份之前我更一版不需要用cuda编译的代码

谢谢大佬，我不着急。我偶然看到您的代码，因为yolo旋转框目标检测本来就很少。我好像看到detectron2里面也有nms_rotate，我也再研究一下。再次感谢您的回复~

**Comment by KolyaIvankov** [comment]
Hey! Sorry, I am no more fluent in Chinese than google translate, but I belive my issue is relevant. Trying to compile on win 11, with CUDA 11.7 and pytorch 1.11 for CUDA 11.3; got message

```
C:\0\yolov5_obb-master\utils\nms_rotated\src\poly_nms_cuda.cu(4): fatal error C1083: Cannot open include file: 'THC/THC.h': No such file or directory
poly_nms_cuda.cu
```
googling shows that [THC was removed from latest version of pytorch](https://github.com/open-mmlab/mmdetection3d/issues/1332)

Could you reproduce this with the newest torch versions?

**Comment by hukaixuan19970627** [comment]
> Hey! Sorry, I am no more fluent in Chinese than google translate, but I belive my issue is relevant. Trying to compile on win 11, with CUDA 11.7 and pytorch 1.11 for CUDA 11.3; got message
> 
> ```
> C:\0\yolov5_obb-master\utils\nms_rotated\src\poly_nms_cuda.cu(4): fatal error C1083: Cannot open include file: 'THC/THC.h': No such file or directory
> poly_nms_cuda.cu
> ```
> 
> googling shows that [THC was removed from latest version of pytorch](https://github.com/open-mmlab/mmdetection3d/issues/1332)
> 
> Could you reproduce this with the newest torch versions?

https://github.com/hukaixuan19970627/yolov5_obb/pull/152

**Comment by lidapengpeng** [comment]
将你的Pytorch版本换成1.10.1，不要用1.11的（这里是为了解决THC.h的问题）

**Comment by matteopantano** [comment]
This requirements should be added to the install.md @hukaixuan19970627
